name: Run Daily Bot

on:
  schedule:
    - cron: '00 14 * * *'  # Every day at 14:00 UTC (adjust as needed)
  workflow_dispatch:      # Allows manual run from GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET_KEY: ${{ secrets.ALPACA_API_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TA-Lib from source
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget unzip
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or 3.11, 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python run_bot.py
